Api 13100/neo bots
livechat/lc-sdk-python pull request #122
Opened 2023-12-07 19:09 UTC by zuczkows

2023-12-08 08:46 UTC, kacperf531 approved these changes

2023-12-08 08:53 UTC, zuczkows commented on livechat/configuration/api/v36.py
> +                id (str): Bot's ID.
Hmm, maybe indeed a template will be better, it's essentially the same, but easier to understand with affect_existing_installations -> delete the bot template and all bots with this ID associated with this template.

2023-12-08 10:25 UTC, zuczkows commented on livechat/configuration/api/v36.py
> +                affect_existing_installations (bool): Indicates whether the template should be applied to existing installations.
👍 I will wait for the official documentation to standardize the docstrings

2023-12-12 14:24 UTC, kacperf531 requested changes
please add `owner_client_id` to `delete_bot_template`, `update_bot_template` and `list_bot_templates` (requests)

not sure if requires any action, but `create_bot` now returns `secret` too. We don't do typed responses, so no big deal, but optionally consider updating docstring

2023-12-13 11:07 UTC, kacperf531 approved these changes

2023-12-13 11:16 UTC, merged