introduce AccessToken dataclass
livechat/lc-sdk-python pull request #128
Opened 2024-02-02 11:09 UTC by kacperf531

https://github.com/livechat/lc-sdk-python/issues/126

2024-02-08 13:01 UTC, skamieniarz commented on livechat/utils/helpers.py
> +        ['self', 'payload', 'token', 'headers', 'date_to', 'date_from']
it requires adding:
```
        if token:
            payload['token'] = str(token)
```
several times. what is the reason here? do you think the current way of adding a token to the payload is too implicit or is it a matter of type conversion to `str`?

2024-02-08 13:09 UTC, skamieniarz commented on livechat/utils/structures.py
> +class Scheme(Enum):
also, it's a top-level definition without a direct link to the token, so i would consider `TokenType` or sth. importing `from livechat.utils.structures import Scheme` does not clearly indicate what scheme we are actually dealing with

2024-02-12 06:41 UTC, zuczkows requested changes
looks good, but add note to changelog

2024-02-26 14:20 UTC, zuczkows approved these changes

2024-02-27 11:25 UTC, merged