API-9774: Introduce support for organization ID in v3.4
livechat/lc-sdk-python pull request #50
Opened 2021-10-11 15:13 UTC by kacperf531

2021-10-12 12:07 UTC, skamieniarz requested changes

2021-10-12 12:07 UTC, skamieniarz commented on livechat/customer/web/client.py
> +            self.query_string = f'?organization_id={str(organization_id)}'
Is is necessary to convert it to string (`str()`) considering previous `isinstance(organization_id, str)`?

2021-10-12 12:07 UTC, skamieniarz commented on livechat/customer/web/client.py
> +        params['organization_id'] = self.organization_id
Is it the only differing item? Perhaps we could check `dir()` or `vars()` of the client object to check presence of either `license_id` or `organization_id` and apply the one present not to duplicate the definitions. Just a suggestion to consider and check.

2021-10-12 12:56 UTC, kacperf531 commented on livechat/customer/web/client.py
> +                'Incorrect or missing `access_token` argument (should be str.)'
Well, this is something I learned when Ola has suggested in my PR in public docs https://github.com/livechat/livechat-public-docs/pull/1030#pullrequestreview-758414441

2021-10-12 12:56 UTC, kacperf531 commented on livechat/customer/web/client.py
> +                'Incorrect or missing `license_id` argument (should be int.)')
same as above

2021-10-12 13:07 UTC, kacperf531 commented on livechat/customer/rtm/client.py
> +        if all([license_id, isinstance(license_id, int)]):
API-9774 post review fixes: 84c537ed54c3cf1d0a1de6cbd63750c2ccc12302

2021-10-13 07:04 UTC, skamieniarz submitted a review, later dismissed

2021-10-13 09:45 UTC, skamieniarz approved these changes

2021-10-13 09:46 UTC, merged