Adding Billing API
livechat/lc-sdk-python pull request #97
Opened 2022-12-15 14:10 UTC by remleinpiotr

2022-12-18 13:08 UTC, zuczkows requested changes

2022-12-18 13:08 UTC, zuczkows commented on livechat/tests/test_billing_api_client.py
> +#     assert client.create_direct_charge().http_version == 'HTTP/2'
Not sure what it means but don't leave commented code. Delete these lines if YAGNI.

2023-01-13 10:11 UTC, remleinpiotr commented on livechat/billing/api/v1.py
> +            Args:
It really exist and Olek already know that at this point it is not added in docs.

2023-01-25 19:42 UTC, zuczkows approved these changes, later dismissed
Approved but correct one typo

2023-01-25 19:42 UTC, zuczkows commented on livechat/billing/api/v1.py
> +        ''' Accepets specific recurrent charge.
```suggestion
        ''' Accepts specific recurrent charge.
```

2023-02-02 09:59 UTC, zuczkows approved these changes, later dismissed

2023-02-02 10:25 UTC, zuczkows approved these changes

2023-02-02 10:29 UTC, merged